#!/bin/bash
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

set -o nounset
set -o pipefail
set -o xtrace

# install_dependencies() - Install required dependencies
function install_dependencies {
    apt-get update
    apt-get install -y -qq wget openjdk-8-jre bridge-utils net-tools bsdmainutils
}

# install_vpp() - Install VPP
function install_vpp {
    local RELEASE=".stable.1609"

    apt-get update
    apt-get install -y -qq apt-transport-https
    echo "deb [trusted=yes] https://nexus.fd.io/content/repositories/fd.io$RELEASE.ubuntu.$(lsb_release -c -s).main/ ./" | tee -a /etc/apt/sources.list.d/99fd.io.list
    apt-get update
    apt-get install -y -qq vpp vpp-lib vpp-plugins vpp-dpdk-dkms
}

# install_vfw_scripts() -
function install_vfw_scripts {
    local version=$(cat /opt/config/demo_artifacts_version.txt)
    local repo_url="https://nexus.onap.org/content/repositories/staging/org/onap/demo/vnf/"

    pushd /opt
    wget https://git.onap.org/demo/plain/vnfs/vFW/scripts/{v_packetgen_init,vpacketgen,run_traffic_fw_demo}.sh
    chmod +x *.sh

    wget "${repo_url}/sample-distribution/${version}/sample-distribution-${version}-hc.tar.gz"
    tar -zmxf sample-distribution-$version-hc.tar.gz
    mv sample-distribution-$version honeycomb

    wget "${repo_url}/vfw/vfw_pg_streams/$version/vfw_pg_streams-$version-demo.tar.gz"
    tar -zmxf vfw_pg_streams-$version-demo.tar.gz
    mv vfw_pg_streams-$version pg_streams

    rm *.tar.gz
    sed -i 's/"restconf-binding-address": "127.0.0.1",/"restconf-binding-address": "0.0.0.0",/g' /opt/honeycomb/config/honeycomb.json

    # TODO(electrocucaracha) Fix it in upstream
    sed -i 's/start vpp/systemctl start vpp/g' v_packetgen_init.sh
    sed -i 's|/opt/honeycomb/sample-distribution-\$VERSION/honeycomb|/opt/honeycomb/honeycomb|g' v_packetgen_init.sh
    mv vpacketgen.sh /etc/init.d/
    update-rc.d vpacketgen.sh defaults
    systemctl start packetgen
    popd
}

mkdir -p /opt/config/
echo "192.168.20.0/24" > /opt/config/protected_net_cidr.txt
echo "192.168.10.100"  > /opt/config/fw_ipaddr.txt
echo "192.168.20.250"  > /opt/config/sink_ipaddr.txt
echo "1.3.0"           > /opt/config/demo_artifacts_version.txt

echo 'vm.nr_hugepages = 1024' >> /etc/sysctl.conf
sysctl -p

install_dependencies
install_vpp
install_vfw_scripts
