#!/bin/bash
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

set -o nounset
set -o pipefail
set -o xtrace

# install_dependencies() - Install required dependencies
function install_dependencies {
    apt install -y software-properties-common
    add-apt-repository -y ppa:openjdk-r/ppa
    apt update

    apt install --allow-unauthenticated -y make wget openjdk-8-jdk apt-transport-https ca-certificates darkstat

    # Configure and run Darkstat
    sed -i "s/START_DARKSTAT=.*/START_DARKSTAT=yes/g" /etc/darkstat/init.cfg
    sed -i "s/INTERFACE=.*/INTERFACE=\"-i eth1\"/g" /etc/darkstat/init.cfg

    systemctl restart darkstat
}

# install_vfw_scripts() -
function install_vfw_scripts {
    pushd /opt
    for script in v_sink_init.sh vsink.sh; do
        wget https://git.onap.org/demo/plain/vnfs/vFW/scripts/$script
        chmod +x $script
    done

    # TODO(electrocucaracha) Fix it in upstream
    sed -i 's/# Provides:/# Provides:          sink/g' vsink.sh

    mv vsink.sh /etc/init.d
    update-rc.d vsink.sh defaults
    systemctl start sink
    popd
}

mkdir -p /opt/config/
echo "192.168.20.0/24" > /opt/config/protected_net_cidr.txt
echo "192.168.10.100"  > /opt/config/fw_ipaddr.txt
echo "192.168.20.250"  > /opt/config/sink_ipaddr.txt
echo "1.3.0"           > /opt/config/demo_artifacts_version.txt
echo "192.168.20.100"  > /opt/config/protected_net_gw.txt
echo "192.168.10.0/24" > /opt/config/unprotected_net.txt

install_dependencies
install_vfw_scripts
